name: Build Android APK

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # گام 1: دریافت کد منبع
      - name: Checkout code
        uses: actions/checkout@v4

      # گام 2: نصب JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      # گام 3: تنظیم Android SDK با اکشن رسمی گوگل
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-root: ${{ github.workspace }}/android-sdk
          components: |
            platforms;android-34
            build-tools;34.0.0

      # گام 4: کش کردن وابستگی‌های Gradle
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # گام 5: ساخت APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # گام 6: آپلود APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release/*.apk